site_name: APIRequest
repo_url: https://github.com/Rooyca/obsidian-api-request/
edit_uri: edit/master/docs/docs/

markdown_extensions:
  - admonition

theme:
  features:
    - content.code.copy
  name: material
  custom_dir: overrides
  palette: 
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - English: 
    - Overview: en/index.md
    - Usage:
      - codeblocks: en/codeblocks.md
      - settings: en/settings.md
      - usecase: en/usecase
  - Español:
    - Inicio: es/index.md
    - Uso:
      - bloques de código: es/codeblocks.md
      - configuraciones: es/settings.md
      - ejemplos de uso: es/usecase
